// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using testMVC.Models;
using testMVC.Data;

namespace testMVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("testMVC.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("ArrivalDate");

                    b.Property<DateTime?>("BirthDate");

                    b.Property<DateTime?>("DepartureDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<byte>("RoomId");

                    b.Property<int?>("RoomId1");

                    b.HasKey("Id");

                    b.HasIndex("RoomId1");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("testMVC.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Capacity");

                    b.Property<int>("Floor");

                    b.Property<bool>("IsOccupied");

                    b.Property<int>("Number");

                    b.Property<float>("Price");

                    b.Property<byte>("RoomTypeId");

                    b.Property<int>("RoomTypeId1");

                    b.HasKey("Id");

                    b.HasIndex("RoomTypeId1");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("testMVC.Models.RoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("RoomType");
                });

            modelBuilder.Entity("testMVC.Models.Customer", b =>
                {
                    b.HasOne("testMVC.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId1");
                });

            modelBuilder.Entity("testMVC.Models.Room", b =>
                {
                    b.HasOne("testMVC.Models.RoomType", "RoomType")
                        .WithMany()
                        .HasForeignKey("RoomTypeId1")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
